scheduler:
  host: "0.0.0.0:50051"
  metrics_port: 9090

worker:
  host: "0.0.0.0:50052"
  metrics_port: 9091
  concurrency: 4
  worker_id: "worker-dev"

client:
  scheduler_addr: "localhost:50051"

retry:
  max_attempts: 3
  initial_backoff: "1s"
  max_backoff: "1m"

logging:
  level: "debug"
  format: "json"

#storage:
  #backend: "memory"
  # Uncomment for PostgreSQL
  # backend: "postgres"
  # postgres:
  #   host: "localhost"
  #   port: 5432
  #   database: "orchestrator"
  #   user: "postgres"
  #   password: "postgres" 

storage:
  backend: "postgres"
  postgres:
    host: "localhost"
    port: 5432
    database: "orchestrator"
    user: "postgres"
    password: "yourpassword"